; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;[env:esp32dev]
;platform = espressif32@6.4.0
;board = esp32dev
;framework = arduino
;monitor_speed = 115200
;
;;Had to back up to this version to get it to work with ESP IDF 4
;lib_deps = askuric/Simple FOC@2.3.2
;
;build_flags =
;    -DSIMPLEFOC_ESP32_USELEDC


[platformio]
default_envs = esp32_idf4

[env:esp32_idf4]
platform = espressif32@6.4.0          ; ESP-IDF 4 / Arduino-ESP32 2.x
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    Simple FOC@2.3.2
build_flags =
    -DSIMPLEFOC_ESP32_USELEDC
lib_archive = false

[env:esp32_idf5]
platform = espressif32@6.13.0         ; ESP-IDF 5 / Arduino-ESP32 3.x
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    Simple FOC@2.4.0
build_flags =
    ; Optional: define any macros for your project
lib_archive = false